### ISSUE TITLE
wss request

### ISSUE THREAD

**Issue by AndySingularity** [feldim2425/OC-Programs#1]
In most cases wss is used instead of ws, that's why implementation of secured websockets would be awesome!
Fingercomp already implemented TLS [here](https://github.com/OpenPrograms/Fingercomp-Programs/tree/master/libtls).
My project requires wss. Please add it! =)

**Comment by feldim2425** [comment]
Added Support for Fingercomp libtls in commit cf23c3fefc79467f1f7d4dd8546553bee91eea91

You have to download the API manually but the normal connection will work without it.
I didn't test the API because I have no Websocket Server with TLS support and I was a bit too lazy to write one. 

Just running the installer again should update the library.
